server:
  hostname: "localhost"
  port: 8000

image_registry:
  enabled: true
  hostname: "localhost"
  port: 5000

upstream_registry:
  enabled: true

admin:
  username: "admin"
  password: "admin"
  email: admin@test.com
  create_account: true

database:
  type: "sqlite"
  path: "${app_home}/server/registry_sqlite.db"

storage:
  type: "lfs"
  path: "${app_home}/server/temp"

notification:
# By default, email notification is disabled. To invite new user, email configuration must be enabled.
  email:
    enabled: false
    smtp_host: ""
    smtp_port: 0
    smtp_user: ""
    smtp_password: ""
    from_address: ""

webapp:
  enable_ui: false
  dist_path: ${app_home}/webapp/build